s.pchelintsev/25: задача "Производитель-потребитель"
NSU-FIT-Operating-Systems/20201-POSIX-Threads pull request #10
Opened 2022-12-04 08:49 UTC by blin-alt-delatb-4toli

Сборка через `make`
Если есть свой `main`, заточенный под названия из ТЗ, можно скомпилить через `make original_names`.

<details open>
    <summary><h1>Обзор очереди</h1></summary>
    `WQ_STRING_CAP` - макс. длина строки, по заданию: 80 символов.
`WQ_QUEUE_CAP` - макс. кол-во хранимых строк, по заданию: 10.

Три семафора - два из них для блокировки при попытке overflow (>WQ_QUEUE_CAP элементов) или underflow (<0 элементов), один используется в кач-ве мутекса.

Помимо семафоров, в структуре хранятся:
- Указатель на строки - думаю, понятно.
- `size_t tail, head` - индексы курсора чтения (`tail`), и записи (`head`).
- `bool valid` - валидность очереди; при вызове `wqInvalidate()` очередь перестаёт быть валидной.
- `int waiting` - Кол-во потоков, которые ждут какой-либо из семафоров. Используется в `wqInvalidate()`, чтобы знать, сколько раз нужно разблокировать семафоры.
</details>

<details>
    <summary open><h1>Функции</h1></summary>
    
### void wqInit(WorkQueue* q)
- Инициализирует очередь, создаёт семафоры, аллоцирует место под строки.

### void wqFree(WorkQueue* q)
- Соотвественно, освобождает ресурсы, аллоцированные в wqInit.

### int wqPut(WorkQueue* q, char* buf)
- Принимает указатель на строку и копирует `min(strlen(buf), WQ_STRING_CAP)` символов в свой внутренний буфер.
- При попытке добавить элемент в полную очередь, блокирует до тех пор, пока место не освободится (через wqPop) или очередь не уронят (через wqInvalidate).
_(TODO: wqFree должен ронять очередь автоматически?)_

### int wqPop(WorkQueue* q, char* buf, size_t bufsize)
- Копирует `min(bufsize, string_length)` символов в buf, где string_length - длина строки, которая содержалась в очереди; возвращает эту длину.
- Даже если строка извлечена не полностью (`bufsize < string_length`), эта запись становится свободной, и может быть перезаписана.
- При попытке вытащить элемент из пустой очереди, блокирует до тех пор, пока не вставят новый элемент (через wqPush, вытащит этот новый элемент), или очередь не уронят (через wqInvalidate, вернёт 0).

### void wqInvalidate(WorkQueue* q)
- Помечает очередь как "невалидную": все попытки добавить или вытащить элемент из очереди не будут изменять очередь, и будут возвращать 0.
- Все потоки, которые были заблокированы в результате underflow/overflow, будут разблокированы, и получат 0 в результате выполнения той блокирующей функции.
</details>

<details>
    <summary><h1>Внутренности</h1></summary>
    
### Push, Pop
`Push` и `Pop` лочат мутекс и сначала проверяют валидность очереди; если она не валидна, то анлочат и сразу выходят с возвращаемым значением 0.

Если же валидна, то увеличивают счётчик заблокированных потоков (`waiting`), анлочат мутекс и уменьшают значение соответствующего семафора (`Push` - семафора-счётчика пустых мест, `Pop` - семафора-счётчика занятых мест). Это позволяет им заблокироваться, если исполнение операции вызвало бы overflow/underflow, и позволяет очереди отслеживать кол-во заблокированных потоков (для разблокирования во время дропа).  

После разблокировки, снова проверяется валидность очереди, лочится мутекс, уменьшается `waiting` и увеличивается счётчик другого семафора (`Push` - увеличивает счётчик занятых мест, `Pop` - счётчик пустых мест), что позволяет противоположной операции разблочиться, если она ждала нас (и сразу же снова заблокироваться на мутексе, лол)  

Далее выполняется сама операция (копирование строки либо из очереди вызывающему, либо от вызывающего в очередь), разблокируется мутекс и функция завершается.

### Invalidate
`Invalidate` блокирует мутекс, что не позволяет другим потокам ни менять семафоры, ни проверять валидность. Очередь маркируется как невалидная, и все потоки, застрявшие на семафорах, разблокируются один за другим (мы знаем, сколько нужно разблокировать, используя `waiting`) чтобы выйти с возвратом 0 (см. проверку валидности после разблока семафора).
</details>

<details>
    <summary><h1>Main</h1></summary>

Создаётся `PRODUCERS` потоков, которые в бесконечном<sup>[1]</sup> цикле суют в очередь строки (в виде номера итерации), `CONSUMERS` потоков, которые всё так же в бесконечном цикле вытаскивают и распечатывают из очереди строки, и 1 Reaper поток, который спустя некоторое время дропает очередь.

Если задефинен `TEST_UNDERFLOWS`, то производители спят 1 секунду, чтобы потребители сделали underflow.

<sup>[1] </sup> Если "метод" очереди возвращает 0, то цикл выходит.
</details>

2022-12-17 08:25 UTC, brzheutskii requested changes

2022-12-17 08:25 UTC, brzheutskii commented on s.pchelintsev/25/main.c
> +void generateRandomString(char* where, size_t max, int i) {
Тут чето у вас какие то усложнения, не совсем понятно зачем. Если вам нужны рандомные строки то свой рандомизатор писать не надо, надо или брать библиотечный, или просто читать из /dev/random и /dev/urandom , это может быть медленнее, но для наших целей более чем достаточно

2022-12-17 08:25 UTC, brzheutskii commented on s.pchelintsev/25/main.c
> +#define max(a, b) ( ((a) > (b)) ? (a) : (b) )
Кажется эти макросы у вас больше нигде не используются, давайте не будет оставлять мертвый код в репозиторие

2022-12-17 08:25 UTC, brzheutskii commented on s.pchelintsev/25/lab25.h
> +	sem_t mutex; // binary semaphore used as a mutex
Честно говоря так и не понял зачем вам еще один семафор/мютекс, в том смысле видно что он используется для инвалидации очереди, но механизм не совсем ясен и не совсем ясень кейс который вы хотели синхронизовывать. Надо будет на паре обсудить

2022-12-17 08:43 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/25/main.c
> +void generateRandomString(char* where, size_t max, int i) {
Ранее эта функция выкидывала строки типа `String #0|String #1|String #2[...]` с рандомным числом `String #%d` для проверки корректного обрезания строки до 80 символов. Потом изменил на формат попроще (`#%d`), но имя функции ради этого не менял.

Если вытаскивать из /dev/random, то не будет понятно - а корректно ли вообще очередь работает, или мы вытаскиваем мусор. В закомменченом-же коде и юзается макрос `min` (сразу же прикрутил `max` чтобы 2 раза не бегать за кодом)

2022-12-17 08:52 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/25/lab25.h
> +	sem_t mutex; // binary semaphore used as a mutex
Помимо инвалидации очереди, этот мутекс блокируется при записи/чтении из очереди, иначе можно наткнуться на кейс где несколько потоков читают/записывают/читают-и-записывают в один слот. Конкретно для чтения/записи можно, конечно, попробовать атомарным интом обойтись, но он используется ещё и для инвалидации очереди.

При инвалидации очереди мы используем счётчик заблокированных потоков (`q->waiting`) для того, чтобы знать, сколько раз нам нужно прибавить значение к семафорам `semFull, semFree`. Без мутекса возможен кейс, где во время инвалидации очереди совершилась операция, которая бы заблокировала поток (under/overflow). Таким образом, он не был бы учтён при прибавлении к семафорам, и этот поток бы остался заблокирован навсегда.

2022-12-17 08:59 UTC, blin-alt-delatb-4toli commented
наверное лучше делать Merge Commit'ы нежели rebase, а то конвы гитхаба не очень с ними дружат

2022-12-27 19:55 UTC, brzheutskii commented
На этой неделе времени у меня не хватило  на то, чтобы вам придумать реализацию поинтереснее без семаформа-мютекса, эта реализация рабочая, поэтому принимаю.

2022-12-27 19:56 UTC, brzheutskii approved these changes

2022-12-27 19:56 UTC, merged