s.pchelintsev/7: Многопоточный `cp -R`
NSU-FIT-Operating-Systems/20201-POSIX-Threads pull request #17
Opened 2022-12-06 20:21 UTC by blin-alt-delatb-4toli

_завтра заполню_

2022-12-17 06:42 UTC, blin-alt-delatb-4toli commented
теперь работает :+1: :+1: :+1: :+1: :+1: :+1: :+1:

2022-12-18 15:48 UTC, brzheutskii requested changes

2022-12-18 15:48 UTC, brzheutskii commented on s.pchelintsev/7/util/queue.c
> +	queue->arr = daNew(sz, NULL);
Честно говоря я не совсем понимаю зачем вам в этой задаче очередь делать на динамическом массиве. Вижу в этом выйгрыш, если вы как то хорошо подобрали коэффициент расширения массива, и он у вас там в итоге не меняется свой размер после изначального быстрого "прогрева", соответственно не вызывается reallloc/malloc , и вы как то там ротируете элементы внутри этогт динамического массива. 
Если так, хотелось бы увидеть подтверждение, что хотя бы на тестовых папках у вас это работает эффективнее чем обычный связный списко с tail и head с точки зрения выделения памяти. 
Если же не так, то у вас там realloc получается попадает в  блок кода под mutex_lock/mutex_unlock, то есть дорогая операция плюс еще и блокирующая, а потоков у вас потенциально может быть очень много по условиям задачи. 
Ну и сравнивая это с очередью на связаном списке с tail/head ,в которой можно вообще обойтись без блокировок если сделать обмен head/tail через lockless механизм (compare and swap, вы тут в нескольких местах всякие atomic используете), совокупный выйгрышь очереди в производительности может быть весьма заметный. 

В общем давайте или подтвердим вашу гипотезу, или сделаем так что бы у вас не было большого количества кода в критических секциях.

Я по коду динамического массива так и не понял как вы

2022-12-18 15:48 UTC, brzheutskii commented on s.pchelintsev/7/util/hashtable.h
> +htTable* newHashtable(size_t cap, void dtor(void*));
Не понял где у вас в программе используется хеш таблица. 
Если вы ее из другой лабы принесли, то поглядите как устроен пул реквест и структура папок по отношению к такому common коду у Александра Янина, его решение лучше тем, что в коммитах и пул реквестах нет мертвого кода которые никак в рамках пул реквесте не используется. 
Если же это просто мертвый код, то давайте уберем его из пул реквеста, лишний код удлиняет время код ревью, у меня его не так много, вам же потом долже ждать когда допроверю ваши лабы разбираясь в мертвом коде.

2022-12-18 15:48 UTC, brzheutskii commented on s.pchelintsev/7/cpy.c
> +	pthread_mutex_unlock(&queueMtx);
В продолжение рассуждений об уменьшении критической секции, переход на lock-free связный список позволит вам тут отказаться от явной синхронизации при использования вашего mutex, а так же можно поставить проверку на размер очереди (сейчас у вас это daSize) и вызывать phread_cond_signal только когда у вас этот размер равен 0, то есть избавиться еще как миниму одной неявной синхронизации.

2022-12-18 15:48 UTC, brzheutskii commented on s.pchelintsev/7/cpy.c
> +				broadcastFinish();
не понял зачем вам broadcatFinish когда он делает тоже самое что и pushWork за исключение изменения active_threads

2022-12-18 15:53 UTC, brzheutskii commented
Ну еще глобально отмечу мысль что написал в разрезе использования dynamic array. Вы там много где используете atomic функции, то есть идете по пути lock free реализации, но при этом самая центральная часть программы, то есть работа с очередью и информирование main потока сделаны можно сказать в обратном стиле, перекрыты мютекосом и условной переменной без особого внимания к тому что там попадает в критическую секцию. При этом подход продолжить все делать в lock free варианте как мо мне выгляди проще даже чем то как вы сейчас сделали. 
Давайте на паре обсудим этот вопрос, поглядим как у вас текущий код проходит тесты и там поймем как пойти дальше. Ну или можете сами сразу пойти по пути lock free, так что бы мы не получили в рамках тестов, дальнейшие пути оптимизации будут сильно более сложные и неочевидные.

2022-12-18 18:23 UTC, blin-alt-delatb-4toli commented
Атомики я использую только для инкремента простого инта, чтобы лочить аж мутекс для простого `+= 1`. Это даже не бликзо к lock-free, и я даже не знаю, где вы углядели у меня замысел уйти в lock-free. Я не знаю, может это субъективно, но имхо пытаться достичь какого-то неведомого lock-free с 100500 возможных багов в разы сложнее чем критические секции.

ТЗ не требует максимальной производительности, минимального лока и прочего. <sup>мне уже больно с 100500 потоков изза которых я не могу запустить валгринд; оперативы не хватает</sup>

2022-12-18 18:57 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/7/cpy.c
> +				broadcastFinish();
### [fixed](https://github.com/NSU-FIT-Operating-Systems/20201-POSIX-Threads/pull/17/commits/f4fd42c391b7cfcd5d9e613ab709a17899559946)

2022-12-18 18:57 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/7/util/hashtable.h
> +htTable* newHashtable(size_t cap, void dtor(void*));
### [fixed](https://github.com/NSU-FIT-Operating-Systems/20201-POSIX-Threads/pull/17/commits/359a825c69d7ba560dc8c4fbda1c30c4c096cb5e)

2022-12-18 19:10 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/7/util/queue.c
> +	queue->arr = daNew(sz, NULL);
CAS связный список, наверное, будет лучше, только его тоже писать и дебажить надо, поэтому он должен вносить реально ощутимую пользу. Я считаю, реаллок - не проблема, поэтому смысла делать LL нет.

(Имхо) реаллок был бы реальной проблемой, если бы мы не могли себе позволить держать этот массив в памяти (ie цель всей программы не в том, чтобы откопировать 100500 папок). Реаллок идёт [степенями двойки](https://github.com/NSU-FIT-Operating-Systems/20201-POSIX-Threads/pull/17/files#diff-6edbd96fb41cf9d5f2df513b98f4c872f45a0bb72f52ebc90ebdd6afd7ffffc5R15-R30) с начальной вместимостью [64](https://github.com/NSU-FIT-Operating-Systems/20201-POSIX-Threads/pull/17/files#diff-8a12923b57954e7a94add0eba84d2629cf4292b307a81309be9f69fc4335e47dR89), поэтому реаллок произойдёт, ну, раз 7 в довольно редких случаях (для 8192 элементов в очереди) **за всю программу**. Также, поскольку раз мы суём элементы **в очередь**, то всё-таки нас заблокировала ось, будь то в кол-ве потоков или открытых файлов. Мы всё равно ждём освобождения этих ресурсов каким-либо потоком из 100500 других, не-занятых-аллоком; аллок не сильно повлияет на время исполнения (если повлияет вообще)

2022-12-18 19:13 UTC, blin-alt-delatb-4toli commented on s.pchelintsev/7/util/queue.c
> +	queue->arr = daNew(sz, NULL);
В копилку про критические секции: они оборачивают только очередь, которая работает **только тогда, когда у нас больше нет ресурсов, чтобы поток продолжил работу**, т.е. нам всё равно остаётся только ждать, пока ось с барского плеча отсыпет потоков или файловых дескрипторов.

2022-12-23 22:01 UTC, brzheutskii commented
По результатам обсуждения на паре и внесенных изменений принимаю пулл реквест

2022-12-23 22:01 UTC, merged