k.romanov/11. Синхронизированный вывод
NSU-FIT-Operating-Systems/20201-POSIX-Threads pull request #19
Opened 2022-12-15 15:27 UTC by k-romanov-20201

```
Модифицируйте программу упр. 1 так, чтобы вывод родительской и дочерней нитей был синхронизован: сначала родительская нить выводила первую строку, затем дочерняя, затем родительская вторую строку и т.д. Используйте мутексы. Рекомендуется использовать мутексы типа PTHREAD_MUTEX_ERRORCHECK.

Явные и неявные передачи управления между нитями (sleep(3C)/usleep(3C), sched_yield(3RT)) и холостые циклы разрешается использовать только на этапе инициализации. 
```

2022-12-17 07:30 UTC, brzheutskii requested changes

2022-12-17 07:30 UTC, brzheutskii commented on k.romanov/11/lab11.c
> +  usleep(1000);
Судя по всем sleep здесь добавлен для изнчальной синхронизации, но не совсем понятно как это гарантирует ее, то есть в этом коде ожидание будет у всех потоков, причем одинаковое, и все равно решающее значение по изначальному захвату мютексов будет иметь представление планировщика о том, кто должен быть первым, а мы как раз от этого хотели избавиться.

2022-12-17 07:30 UTC, brzheutskii commented on k.romanov/11/lab11.c
> +  for (size_t i = 0; i < NUM_THREADS; i++) {
В продожение про изначальную инициализацию, то что вы сделали масштабируемую версию это очень хорошо, но давайте все таки и задание учтем, то есть сделаем так что бы родительский main поток то же занимался выводом строк и был первым по порядку. Это вам и вопрос синхронизации позволит решить иначе и решение будет соответствовать условиям задачи

2022-12-28 07:35 UTC, k-romanov-20201 commented
sleep поставлен, чтобы дождаться того, что каждый поток был создан и взял свой уникальный мутекс, при этом остаётся один мутекс незахваченный, и на него претендует только один поток, который и становится первым. Остальные потоки пытаются взять мутексы, взятые другими на инициализации, но уже после sleep'а.

2022-12-30 00:22 UTC, brzheutskii approved these changes

2022-12-30 00:23 UTC, merged