8-9. Вычисление Пи пока не надоест
NSU-FIT-Operating-Systems/20201-POSIX-Threads pull request #28
Opened 2022-12-24 10:18 UTC by k-romanov-20201

```
9. Вычисление Пи пока не надоест

Модифицируйте программу упражнения 8 так, чтобы сама по себе она не завершалась. Вместо этого, после нажания ^-C (после получения сигнала SIGINT) программа должна как можно скорее завершаться, собирать частичные суммы ряда и выводить полученное приближение числа.

Рекомендации: ожидаемое решение состоит в том, что вы установите обработчик SIGINT. Этот обработчик должен устанавливать глобальную флаговую переменную. Вычислительные нити должны просматривать значение флага через некоторое количество итераций, например через 1000000, и выходить при помощи pthread_exit, если флаг установлен. Подумайте, как минимизировать ошибку, обусловленную тем, что разные потоки к моменту завершения успели пройти разное количество итераций. Скорее всего, такая минимизация должна обеспечиваться за счет увеличения времени между получением сигнала и выходом.
```

2022-12-25 22:14 UTC, brzheutskii requested changes

2022-12-25 22:14 UTC, brzheutskii commented on k.romanov/8/pi.c
> +	printf("\nReceived SIGINT, printing result\n");
printf нельзя использовать в обработчике сигнала, давайте на паре расскажете почему

2022-12-25 22:14 UTC, brzheutskii commented on k.romanov/8/pi.c
> +	pthread_cond_broadcast(&cond);
Тут у вас таже беда что и в 6 задачке, нет гарантии что ваши потоки дойдут до wait раньше broadcast. Надо бы поправить

2022-12-25 22:14 UTC, brzheutskii commented on k.romanov/8/pi.c
> +		for(size_t i = 0; i < SUM_GRANULARITY; i++){
На паре мы с вами обсуждали то, что такая реализация хоть и в купе с вашей изначальной синхронизацией неплоха, но страдает от того, что в момент когда вы решите закончить работу программы неизвестно как выдавался приоритет потокам, особенно если их пользователь запросил много. Запросто может получиться так, что больше всех работал 1 поток, и например 1000й, а все остальные поработали значительно меньше. С вашим кодом тут вообще интересная ситуация, если вы захотите создать много потоков, и нажмете Ctrl+C когда они еще не все создались, то у вас там половина потоков подвиснет на cond_wait. Если же повезет и все пройдут эту стадию, то могут не дойти дальше до старта цикла, так как вы нажмете Ctrl+C раньше, а значит вообще ничего не успеют посчитать. Ну а особенность алгоритма такая, что более ранние итерации дают наибольший вклад, и вам поидее надо бы куда важнее посчитать именно ранние операции чем какие нибудь там 1000е в 1000м потоке.

На паре я вам предлагал сделать реализацию с атомарным номером блока для подсчета который потоки  атомарно увеличивают когда взялись считать его. Думаю это было бы идеальным такое тут сделать

2022-12-27 20:32 UTC, brzheutskii commented
Реализация валидная, но давайте все таки сделаем еще на  atomic изменениях номера блока (там есть специальная функция для того что бы сделать сначала сложение а потом взять значение полученое). 

И давайте сделаем тест, вашу текущую реализацию возьмем и с атомиком, ну и обе ограничим не по времени и ctrl-c, а по количеству итераций, возьмите какое нибудь большое число типа 200кк , и потоков возьмити тоже прилично, 10к например. Замерьте у обоих реализаций время работы и вывод `strace -cqf` , поглядим насколько большой вклад дает mutex

2022-12-29 10:06 UTC, k-romanov-20201 commented
![Screenshot_262](https://user-images.githubusercontent.com/115343522/209935971-1d06eca3-c343-4f15-b8a9-6fbf09907df2.png)
![Screenshot_261](https://user-images.githubusercontent.com/115343522/209935974-ff556c14-105a-41e3-b4d7-b0378153e2cc.png)

2022-12-29 10:08 UTC, k-romanov-20201 commented
Сравнение версии с атомарным счётчиком и версии с мутексом.

2022-12-29 10:28 UTC, merged